//
// Created by Hippo on 12/28/2015.
//

#ifndef IMAGE_JAVA_WRAPPER_H
#define IMAGE_JAVA_WRAPPER_H

#include <jni.h>

#define IMAGE_TILE_TYPE_SMALL 0x00
#define IMAGE_SMALL_TILE_CONTENT_SIZE 254
#define IMAGE_SMALL_TILE_BORDER_SIZE 1
#define IMAGE_SMALL_TILE_SIZE 256

#define IMAGE_TILE_TYPE_LARGE 0x01
#define IMAGE_LARGE_TILE_CONTENT_SIZE 508
#define IMAGE_LARGE_TILE_BORDER_SIZE 2
#define IMAGE_LARGE_TILE_SIZE 512

JNIEnv *get_env();

#endif // IMAGE_JAVA_WRAPPER_H
